env_name: "Taxi-v4"
is_rainy: False
rainy_probability: 0.8
fickle_passenger: False
fickle_probability: 0.05
render_mode: "rgb_array" # "human" for visualization, "rgb_array" for headless mode
episodes: 5000
seed: 42

init_alpha: 0.5
min_alpha: 0.01
alpha_decay_rate: 0.99890
alpha_decay_law: "exponential" # ["linear", "exponential", "logarithmic"] 

gamma: 0.99
max_steps: 500

control_algorithm: "mc_control" # ["mc_control", "sarsa", "q_learning", "double_q_learning"]
theta: 1e-8 # Convergence threshold for value iteration (planning engine)

mc_control_params:
  first_visit: True

sarsa_params:
  init_epsilon: 1.0

policy: "epsilon_greedy" # ["epsilon_greedy", "softmax", "ucb", "thompson_sampling"]

epsilon_greedy_params:
  init_epsilon: 1.0
  min_epsilon: 0.05
  decay_rate: 0.99915 
  decay_law: "exponential" # ["linear", "exponential", "logarithmic"]

softmax_params:
  init_temperature: 1.0
  min_temperature: 0.01
  decay_rate: 0.99870
  decay_law: "exponential" # ["linear", "exponential", "logarithmic"]

ucb_params:
  c: 1.414 # A higher value encourages more exploration, while a lower value encourages more exploitation. The optimal value of c can depend on the specific environment and the scale of the rewards.

thompson_sampling_params:
  alpha: 1.0 # Alpha controls the scale of the distribution
  beta: 1.0 # Beta controls the shift such that the standard deviation shrinks more slowly.
