env_name: "FrozenLake-v1"
is_slippery: True
render_mode: "rgb_array" # "human" for visualization, "rgb_array" for headless mode
episodes: 5000
seed: 42

value_agent_params:
  algorithm_name: "td_lambda" # ["td_zero", "td_lambda"]
  init_alpha: 0.1
  min_alpha: 0.005
  decay_steps: 3000
  decay_rate: 0.999
  decay_law: "exponential" # ["linear", "exponential", "logarithmic"] 
  gamma: 0.99
  lambda: 0.8
  theta: 1e-8 # Convergence threshold for value iteration (planning engine)
